# Generated by Django 5.2.11 on 2026-03-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubuser',
            name='profile_owner',
        ),
        migrations.DeleteModel(
            name='GitHubRepo',
        ),
        migrations.DeleteModel(
            name='GitHubUser',
        ),
    ]
