# Generated by Django 5.2.11 on 2026-03-05 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.PositiveBigIntegerField(unique=True)),
                ('login', models.CharField(max_length=128, unique=True)),
                ('avatar_url', models.URLField()),
                ('name', models.CharField(max_length=128, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('bio', models.TextField(null=True)),
                ('profile_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo_id', models.PositiveBigIntegerField(unique=True)),
                ('name', models.CharField(max_length=256)),
                ('full_name', models.CharField(max_length=256)),
                ('private', models.BooleanField()),
                ('html_url', models.URLField()),
                ('description', models.TextField(null=True)),
                ('language', models.CharField(max_length=64, null=True)),
                ('archived', models.BooleanField()),
                ('forks_count', models.IntegerField()),
                ('stargazers_count', models.IntegerField()),
                ('open_issues_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.githubuser')),
            ],
        ),
    ]
