# Generated by Django 5.2.11 on 2026-03-15 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubPullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_owner_login', models.CharField(max_length=128)),
                ('pr_owner_id', models.PositiveBigIntegerField()),
                ('html_url', models.URLField()),
                ('github_id', models.PositiveBigIntegerField(unique=True)),
                ('number', models.IntegerField()),
                ('state', models.CharField(max_length=128)),
                ('locked', models.BooleanField()),
                ('title', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(null=True)),
                ('merged_at', models.DateTimeField(null=True)),
                ('draft', models.BooleanField()),
                ('additions', models.IntegerField()),
                ('deletions', models.IntegerField()),
                ('changed_files', models.IntegerField()),
                ('commits', models.IntegerField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.githubrepo')),
            ],
        ),
    ]
