# Generated by Django 5.2.11 on 2026-03-25 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_githubpullrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='github_owner_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='github_owner_login',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='GitHubIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.PositiveBigIntegerField(unique=True)),
                ('html_url', models.URLField()),
                ('state', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField(max_length=512, null=True)),
                ('author_id', models.PositiveBigIntegerField()),
                ('author_login', models.CharField(max_length=128)),
                ('closed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('number', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.githubrepo')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubPRReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.PositiveBigIntegerField(unique=True)),
                ('reviewer_id', models.PositiveBigIntegerField()),
                ('reviewer_login', models.CharField(max_length=128)),
                ('body', models.TextField(max_length=512, null=True)),
                ('html_url', models.URLField()),
                ('submitted_at', models.DateTimeField()),
                ('commit_id', models.CharField(max_length=256, null=True)),
                ('state', models.CharField(max_length=64)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.githubpullrequest')),
            ],
        ),
    ]
