# Generated by Django 5.2.11 on 2026-04-02 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_githubrepo_github_owner_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubpullrequest',
            name='additions',
        ),
        migrations.RemoveField(
            model_name='githubpullrequest',
            name='changed_files',
        ),
        migrations.RemoveField(
            model_name='githubpullrequest',
            name='commits',
        ),
        migrations.RemoveField(
            model_name='githubpullrequest',
            name='deletions',
        ),
        migrations.AlterField(
            model_name='githubprreview',
            name='pull_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='integrations.githubpullrequest'),
        ),
    ]
